# Data Preprocessing and Feature Engineering

This notebook performs comprehensive data preprocessing and feature engineering on the 'expanded_sleep_health_dataset.csv' to prepare it for machine learning tasks. The steps include data loading, initial inspection, handling missing values, encoding categorical features, detecting and treating outliers, and feature scaling.

In [167]:
import numpy as np
import pandas as pd

## 1. Library Imports

**Logic:** This section imports the necessary Python libraries for data manipulation, numerical operations, and machine learning preprocessing.

**Requirements:**
- `pandas`: For data loading and manipulation.
- `numpy`: For numerical operations.
- `sklearn.preprocessing.LabelEncoder`: For encoding categorical variables.
- `sklearn.preprocessing.MinMaxScaler`: For scaling numerical features.

In [168]:
df = pd.read_csv('/content/expanded_sleep_health_dataset.csv')

## 2. Data Loading

**Logic:** The dataset is loaded into a pandas DataFrame from the specified CSV file.

**Requirements:** The 'expanded_sleep_health_dataset.csv' file should be available at the path `/content/expanded_sleep_health_dataset.csv`.

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                1500 non-null   int64
 1   Gender                   1500 non-null   object
 2   Age                      1500 non-null   int64
 3   Occupation               1500 non-null   object
 4   Sleep Duration           1500 non-null   float64
 5   Quality of Sleep         1500 non-null   int64
 6   Physical Activity Level  1500 non-null   int64
 7   Stress Level             1500 non-null   int64
 8   BMI Category             1500 non-null   object
 9   Blood Pressure           1500 non-null   object
 10  Heart Rate               1500 non-null   int64
 11  Daily Steps              1500 non-null   int64
 12  Sleep Disorder           539 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 152.5+ KB

In [170]:
df.describe()

         Person ID          Age  ...   Heart Rate  Daily Steps
count  1500.000000  1500.000000  ...  1500.000000   1500.00000
mean    750.500000    48.394667  ...    74.763333   6119.56600
std     433.157015    18.160510  ...    12.237340   2823.00209
min       1.000000    18.000000  ...    43.000000   1000.00000
25%     375.750000    33.000000  ...    66.000000   3983.50000
50%     750.500000    47.000000  ...    75.000000   5823.50000
75%    1125.250000    64.000000  ...    83.000000   8028.00000
max    1500.000000    80.000000  ...   109.000000  16036.00000

[8 rows x 8 columns]

In [171]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             961
dtype: int64

## 3. Initial Data Inspection

**Logic:** This section provides an initial overview of the dataset, including data types, non-null counts, basic descriptive statistics, and the sum of null values per column. This helps in understanding the data structure and identifying potential issues like missing values or incorrect data types.

**Methods Used:**
- `df.info()`: Displays a concise summary of the DataFrame.
- `df.describe()`: Generates descriptive statistics of the numerical columns.
- `df.isnull().sum()`: Calculates the number of missing values for each column.

In [172]:
if 'Person ID' in df.columns:
  df.drop('Person ID', axis =1,inplace=True)

## 4. Drop 'Person ID' Column

**Logic:** The 'Person ID' column is dropped as it is a unique identifier and not relevant for machine learning model training.

**Methods Used:**
- `df.drop()`: Removes the specified column from the DataFrame.

In [173]:
df[['Systolic_BP','Diastolic_BP']]= df['Blood Pressure'].str.split('/',expand=True)
df['Systolic_BP'] = pd.to_numeric(df['Systolic_BP'],errors='coerce')
df['Diastolic_BP'] = pd.to_numeric(df['Diastolic_BP'],errors='coerce')
df.drop('Blood Pressure',axis=1,inplace=True)

In [174]:
df['Systolic_BP'].fillna(df['Systolic_BP'].mean(), inplace=True)
df['Diastolic_BP'].fillna(df['Diastolic_BP'].mean(), inplace=True)

/tmp/ipykernel_8238/1335821335.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Systolic_BP'].fillna(df['Systolic_BP'].mean(), inplace=True)
/tmp/ipykernel_8238/1335821335.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Diastolic_BP'].fillna(df['Diastolic_BP'].mean(), inplace=True)

## 5. Process 'Blood Pressure' Column

**Logic:** The 'Blood Pressure' column, which is in 'Systolic/Diastolic' string format, is split into two separate numerical columns: 'Systolic_BP' and 'Diastolic_BP'. Missing values introduced during conversion or originally present are filled with the mean of their respective columns.

**Methods Used:**
- `str.split('/')`: Splits the string column into two new columns.
- `pd.to_numeric()`: Converts the new columns to numeric types, coercing errors.
- `fillna()`: Fills any resulting NaN values with the mean of the column.

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   1500 non-null   object
 1   Age                      1500 non-null   int64
 2   Occupation               1500 non-null   object
 3   Sleep Duration           1500 non-null   float64
 4   Quality of Sleep         1500 non-null   int64
 5   Physical Activity Level  1500 non-null   int64
 6   Stress Level             1500 non-null   int64
 7   BMI Category             1500 non-null   object
 8   Heart Rate               1500 non-null   int64
 9   Daily Steps              1500 non-null   int64
 10  Sleep Disorder           539 non-null    object
 11  Systolic_BP              1500 non-null   int64
 12  Diastolic_BP             1500 non-null   float64
dtypes: float64(2), int64(7), object(4)
memory usage: 152.5+ KB

In [176]:
df

      Gender  Age         Occupation  ...  Sleep Disorder  Systolic_BP  Diastolic_BP
0       Male   41              Nurse  ...             NaN          111         71.15
1       Male   42  Software Engineer  ...             NaN          129         85.85
2     Female   45             Doctor  ...             NaN          119         79.35
3       Male   24             Writer  ...             NaN           98         62.70
4     Female   18        Salesperson  ...             NaN          110         66.50
...      ...  ...                ...  ...             ...          ...           ...
1495    Male   63           Engineer  ...             NaN          131         90.15
1496    Male   70             Lawyer  ...      Narcolepsy          117         74.05
1497    Male   23           Engineer  ...     Sleep Apnea          110         67.50
1498    Male   76           Engineer  ...        Insomnia          126         86.90
1499  Female   22           Engineer  ...      Narcolepsy          114         78.10

[1500 rows x 13 columns]

## 6. Update 'Sleep Disorder' Column

**Logic:** Missing values in the 'Sleep Disorder' column are initially filled with 'None'. Subsequently, this column is transformed into a boolean type, indicating the presence (True) or absence (False) of any sleep disorder.

**Methods Used:**
- `fillna('None')`: Replaces missing values with the string 'None'.
- `.apply(lambda x: x != 'None')`: Converts the column to a boolean type based on whether the value is 'None'.

In [177]:
df['Sleep Disorder']= df['Sleep Disorder'].fillna('None')

In [178]:
df

      Gender  Age         Occupation  ...  Sleep Disorder  Systolic_BP  Diastolic_BP
0       Male   41              Nurse  ...            None          111         71.15
1       Male   42  Software Engineer  ...            None          129         85.85
2     Female   45             Doctor  ...            None          119         79.35
3       Male   24             Writer  ...            None           98         62.70
4     Female   18        Salesperson  ...            None          110         66.50
...      ...  ...                ...  ...             ...          ...           ...
1495    Male   63           Engineer  ...            None          131         90.15
1496    Male   70             Lawyer  ...      Narcolepsy          117         74.05
1497    Male   23           Engineer  ...     Sleep Apnea          110         67.50
1498    Male   76           Engineer  ...        Insomnia          126         86.90
1499  Female   22           Engineer  ...      Narcolepsy          114         78.10

[1500 rows x 13 columns]

In [138]:
df['Sleep Disorder'] = df['Sleep Disorder'].apply(lambda x: x != 'None')

In [179]:
df['Sleep Disorder'] = df['Sleep Disorder'].apply(lambda x: 0 if x == 'None' else 1)

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   1500 non-null   object
 1   Age                      1500 non-null   int64
 2   Occupation               1500 non-null   object
 3   Sleep Duration           1500 non-null   float64
 4   Quality of Sleep         1500 non-null   int64
 5   Physical Activity Level  1500 non-null   int64
 6   Stress Level             1500 non-null   int64
 7   BMI Category             1500 non-null   object
 8   Heart Rate               1500 non-null   int64
 9   Daily Steps              1500 non-null   int64
 10  Sleep Disorder           1500 non-null   int64
 11  Systolic_BP              1500 non-null   int64
 12  Diastolic_BP             1500 non-null   float64
dtypes: float64(2), int64(8), object(3)
memory usage: 152.5+ KB

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   1500 non-null   object
 1   Age                      1500 non-null   int64
 2   Occupation               1500 non-null   object
 3   Sleep Duration           1500 non-null   float64
 4   Quality of Sleep         1500 non-null   int64
 5   Physical Activity Level  1500 non-null   int64
 6   Stress Level             1500 non-null   int64
 7   BMI Category             1500 non-null   object
 8   Heart Rate               1500 non-null   int64
 9   Daily Steps              1500 non-null   int64
 10  Sleep Disorder           1500 non-null   int64
 11  Systolic_BP              1500 non-null   int64
 12  Diastolic_BP             1500 non-null   float64
dtypes: float64(2), int64(8), object(3)
memory usage: 152.5+ KB

In [182]:
df.isnull().sum()

Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
Systolic_BP                0
Diastolic_BP               0
dtype: int64

## 7. Categorical Feature Encoding

**Logic:** Categorical features ('Gender', 'BMI Category', 'Occupation') are converted into numerical representations suitable for machine learning models.

**Methods Used:**
- **Gender:** `LabelEncoder` from `sklearn.preprocessing` is used to convert 'Male' and 'Female' to numerical labels (0 and 1).
- **BMI Category:** A `map` function is used to convert 'Underweight', 'Normal', 'Overweight', and 'Obese' to ordinal numerical values (0, 1, 2, 3).
- **Occupation:** One-hot encoding is applied using `pd.get_dummies()` to create binary columns for each occupation, dropping the first category to avoid multicollinearity.

In [183]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [184]:
df['Gender']

0       1
1       1
2       0
3       1
4       0
       ..
1495    1
1496    1
1497    1
1498    1
1499    0
Name: Gender, Length: 1500, dtype: int64

In [185]:
df['BMI Category'] = df['BMI Category'].map({
    'Underweight': 0,
    'Normal': 1,
    'Overweight': 2,
    'Obese': 3
})

In [186]:
df['BMI Category']

0       1
1       2
2       1
3       1
4       2
       ..
1495    3
1496    1
1497    2
1498    2
1499    1
Name: BMI Category, Length: 1500, dtype: int64

In [187]:
df

      Gender  Age         Occupation  ...  Sleep Disorder  Systolic_BP  Diastolic_BP
0          1   41              Nurse  ...               0          111         71.15
1          1   42  Software Engineer  ...               0          129         85.85
2          0   45             Doctor  ...               0          119         79.35
3          1   24             Writer  ...               0           98         62.70
4          0   18        Salesperson  ...               0          110         66.50
...      ...  ...                ...  ...             ...          ...           ...
1495       1   63           Engineer  ...               0          131         90.15
1496       1   70             Lawyer  ...               1          117         74.05
1497       1   23           Engineer  ...               1          110         67.50
1498       1   76           Engineer  ...               1          126         86.90
1499       0   22           Engineer  ...               1          114         78.10

[1500 rows x 13 columns]

In [188]:
df = pd.get_dummies(df, columns=['Occupation'], drop_first=True)

In [189]:
df.drop_duplicates(inplace=True)

## 8. Remove Duplicate Rows

**Logic:** Duplicate rows in the DataFrame are removed to ensure data integrity and prevent biases in analysis or model training.

**Methods Used:**
- `df.drop_duplicates(inplace=True)`: Identifies and removes duplicate rows directly from the DataFrame.

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Gender                           1500 non-null   int64
 1   Age                              1500 non-null   int64
 2   Sleep Duration                   1500 non-null   float64
 3   Quality of Sleep                 1500 non-null   int64
 4   Physical Activity Level          1500 non-null   int64
 5   Stress Level                     1500 non-null   int64
 6   BMI Category                     1500 non-null   int64
 7   Heart Rate                       1500 non-null   int64
 8   Daily Steps                      1500 non-null   int64
 9   Sleep Disorder                   1500 non-null   int64
 10  Systolic_BP                      1500 non-null   int64
 11  Diastolic_BP                     1500 non-null   float64
 12  Occupation_Artist                1500 non-null   bool
 13  Occupation_Chef                  1500 non-null   bool
 14  Occupation_Doctor                1500 non-null   bool
 15  Occupation_Engineer              1500 non-null   bool
 16  Occupation_Lawyer                1500 non-null   bool
 17  Occupation_Manager               1500 non-null   bool
 18  Occupation_Nurse                 1500 non-null   bool
 19  Occupation_Sales Representative  1500 non-null   bool
 20  Occupation_Salesperson           1500 non-null   bool
 21  Occupation_Scientist             1500 non-null   bool
 22  Occupation_Software Engineer     1500 non-null   bool
 23  Occupation_Student               1500 non-null   bool
 24  Occupation_Teacher               1500 non-null   bool
 25  Occupation_Writer                1500 non-null   bool
dtypes: bool(14), float64(2), int64(10)
memory usage: 161.3 KB

## 9. Outlier Detection and Treatment (Winsorization)

**Logic:** This section identifies and treats outliers in selected numerical columns using the Interquartile Range (IQR) method. Outliers are capped at the upper and lower bounds (Q1 - 1.5*IQR and Q3 + 1.5*IQR) to reduce their influence on the model, a technique known as Winsorization.

**Methods Used:**
- `df.quantile()`: Calculates the first (Q1) and third (Q3) quartiles.
- `IQR = Q3 - Q1`: Computes the Interquartile Range.
- `df.clip()`: Caps values outside the calculated IQR bounds.

In [191]:
df['Stress Level']

0       10
1        5
2        7
3        5
4        4
        ..
1495     4
1496     9
1497     9
1498     5
1499     5
Name: Stress Level, Length: 1500, dtype: int64

In [192]:
import numpy as np

num_df = df.select_dtypes(include=[np.number])

Q1 = num_df.quantile(0.25)
Q3 = num_df.quantile(0.75)
IQR = Q3 - Q1

outliers = ((num_df < (Q1 - 1.5 * IQR)) | (num_df > (Q3 + 1.5 * IQR)))

print(outliers.sum())

Gender                      0
Age                         0
Sleep Duration              4
Quality of Sleep           23
Physical Activity Level    10
Stress Level                0
BMI Category                0
Heart Rate                  6
Daily Steps                 4
Sleep Disorder              0
Systolic_BP                 0
Diastolic_BP                0
dtype: int64

In [193]:
outlier_rows = num_df[((num_df < (Q1 - 1.5 * IQR)) |
                       (num_df > (Q3 + 1.5 * IQR))).any(axis=1)]

print(outlier_rows)

      Gender  Age  Sleep Duration  ...  Sleep Disorder  Systolic_BP  Diastolic_BP
20         0   69             7.4  ...               1          117         80.05
22         1   61             6.8  ...               0          126         82.90
85         0   62             8.1  ...               0          124         77.60
108        0   63             7.4  ...               1          117         77.05
316        1   23             7.4  ...               0          115         78.75
326        1   52             7.3  ...               1          120         73.00
340        1   67             7.5  ...               0          123         76.95
366        0   71             7.3  ...               0          145         97.25
429        0   70             8.7  ...               1          127         86.55
449        1   52             7.7  ...               0          130         84.50
461        1   69             7.2  ...               1          141         90.65
510        0   73             8.6  ...               1          146         96.90
539        0   42             8.1  ...               0          117         81.05
565        0   73             7.6  ...               0          122         80.30
572        1   49             7.7  ...               1          141         91.65
595        0   79             8.0  ...               1          109         65.85
604        0   77             7.8  ...               0          141         87.65
686        1   56             7.1  ...               0          116         73.40
708        1   72             7.1  ...               1          115         69.75
732        1   63             5.2  ...               1          128         81.20
746        1   47             5.2  ...               0          137         86.05
752        1   23             9.3  ...               0          100         65.00
773        0   24             6.0  ...               0          102         70.30
780        0   39             8.7  ...               0          103         68.95
806        0   34             7.6  ...               0          124         83.60
893        0   68             7.7  ...               0          120         76.00
916        0   67             6.4  ...               0          122         82.30
920        1   34             5.3  ...               1          115         77.75
952        0   69             6.7  ...               1          121         74.65
1096       0   68             5.1  ...               1          130         87.50
1102       0   47             5.4  ...               0          126         86.90
1106       0   75             7.4  ...               0          140         87.00
1111       0   68             8.5  ...               0          106         64.90
1112       0   63             7.5  ...               0          119         75.35
1115       1   21             7.3  ...               1          119         76.35
1232       0   21             6.7  ...               1          107         73.55
1244       1   62             9.0  ...               0          135         84.75
1250       1   63             6.5  ...               1          136         91.40
1270       0   78             7.3  ...               1          136         93.40
1348       0   63             7.2  ...               0          106         71.90
1408       0   35             8.6  ...               1          111         71.15
1453       0   49             7.9  ...               0          120         82.00
1480       0   42             7.7  ...               0          102         62.30
1483       0   57             6.8  ...               1          122         78.30
1496       1   70             8.6  ...               1          117         74.05

[45 rows x 12 columns]

In [194]:
col = 'Physical Activity Level'

outliers_qos = df[(df[col] < (Q1[col] - 1.5 * IQR[col])) |
                  (df[col] > (Q3[col] + 1.5 * IQR[col]))]

print(outliers_qos)

      Gender  Age  ...  Occupation_Teacher  Occupation_Writer
108        0   63  ...                True              False
461        1   69  ...               False              False
752        1   23  ...               False              False
773        0   24  ...                True              False
780        0   39  ...               False              False
916        0   67  ...               False              False
1111       0   68  ...               False              False
1408       0   35  ...               False              False
1453       0   49  ...               False              False
1480       0   42  ...               False              False

[10 rows x 26 columns]

In [195]:
print(outliers_qos[col])

108     180
461     180
752     173
773     180
780     180
916     171
1111    169
1408    176
1453    180
1480    180
Name: Physical Activity Level, dtype: int64

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Gender                           1500 non-null   int64
 1   Age                              1500 non-null   int64
 2   Sleep Duration                   1500 non-null   float64
 3   Quality of Sleep                 1500 non-null   int64
 4   Physical Activity Level          1500 non-null   int64
 5   Stress Level                     1500 non-null   int64
 6   BMI Category                     1500 non-null   int64
 7   Heart Rate                       1500 non-null   int64
 8   Daily Steps                      1500 non-null   int64
 9   Sleep Disorder                   1500 non-null   int64
 10  Systolic_BP                      1500 non-null   int64
 11  Diastolic_BP                     1500 non-null   float64
 12  Occupation_Artist                1500 non-null   bool
 13  Occupation_Chef                  1500 non-null   bool
 14  Occupation_Doctor                1500 non-null   bool
 15  Occupation_Engineer              1500 non-null   bool
 16  Occupation_Lawyer                1500 non-null   bool
 17  Occupation_Manager               1500 non-null   bool
 18  Occupation_Nurse                 1500 non-null   bool
 19  Occupation_Sales Representative  1500 non-null   bool
 20  Occupation_Salesperson           1500 non-null   bool
 21  Occupation_Scientist             1500 non-null   bool
 22  Occupation_Software Engineer     1500 non-null   bool
 23  Occupation_Student               1500 non-null   bool
 24  Occupation_Teacher               1500 non-null   bool
 25  Occupation_Writer                1500 non-null   bool
dtypes: bool(14), float64(2), int64(10)
memory usage: 161.3 KB

In [197]:
outlier_cols = [
    'Sleep Duration',
    'Quality of Sleep',
    'Physical Activity Level',
    'Heart Rate',
    'Daily Steps'
]

In [198]:
for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

In [199]:

print(df[outlier_cols].describe())

       Sleep Duration  Quality of Sleep  ...   Heart Rate   Daily Steps
count     1500.000000       1500.000000  ...  1500.000000   1500.000000
mean         7.752267          5.840667  ...    74.761333   6117.278000
std          0.899300          1.745082  ...    12.231780   2815.976085
min          5.400000          2.000000  ...    43.000000   1000.000000
25%          7.200000          5.000000  ...    66.000000   3983.500000
50%          7.700000          6.000000  ...    75.000000   5823.500000
75%          8.400000          7.000000  ...    83.000000   8028.000000
max         10.000000         10.000000  ...   108.500000  14094.750000

[8 rows x 5 columns]

In [200]:
import numpy as np

num_df = df.select_dtypes(include=[np.number])

Q1 = num_df.quantile(0.25)
Q3 = num_df.quantile(0.75)
IQR = Q3 - Q1

outliers = ((num_df < (Q1 - 1.5 * IQR)) | (num_df > (Q3 + 1.5 * IQR)))

print(outliers.sum())

Gender                     0
Age                        0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
Systolic_BP                0
Diastolic_BP               0
dtype: int64

## 10. Feature Scaling (Min-Max Scaling)

**Logic:** The features (X) are separated from the target variable (y), 'Stress Level'. The numerical features in X are then scaled using `MinMaxScaler` to bring them within a specific range (typically 0 to 1). This is crucial for algorithms that are sensitive to the magnitude of feature values.

**Methods Used:**
- `df.drop()`: Separates features (X) and target (y).
- `MinMaxScaler`: Scales numerical features to a 0-1 range.
- `pd.DataFrame()`: Converts the scaled NumPy array back into a pandas DataFrame.

In [201]:
X = df.drop('Stress Level', axis=1)
y = df['Stress Level']

In [202]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [203]:
import pandas as pd

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [204]:
final_df = pd.concat([X_scaled, y], axis=1)

## 11. Final DataFrame Preparation and Export

**Logic:** The scaled feature DataFrame (`X_scaled`) is concatenated with the target variable (`y`) to form the final preprocessed DataFrame (`final_df`). This DataFrame is then inspected and saved to a new CSV file for future use.

**Methods Used:**
- `pd.concat()`: Combines the features and target into a single DataFrame.
- `final_df.describe()`: Provides descriptive statistics for the final DataFrame.
- `final_df.to_csv()`: Exports the final DataFrame to a CSV file named 'final_df.csv'.

In [205]:
final_df.describe()

            Gender          Age  ...  Occupation_Writer  Stress Level
count  1500.000000  1500.000000  ...        1500.000000   1500.000000
mean      0.482667     0.490237  ...           0.066667      6.012000
std       0.499866     0.292911  ...           0.249527      2.366909
min       0.000000     0.000000  ...           0.000000      1.000000
25%       0.000000     0.241935  ...           0.000000      4.000000
50%       0.000000     0.467742  ...           0.000000      6.000000
75%       1.000000     0.741935  ...           0.000000      8.000000
max       1.000000     1.000000  ...           1.000000     10.000000

[8 rows x 26 columns]

In [206]:
final_df

      Gender       Age  ...  Occupation_Writer  Stress Level
0        1.0  0.370968  ...                0.0            10
1        1.0  0.387097  ...                0.0             5
2        0.0  0.435484  ...                0.0             7
3        1.0  0.096774  ...                1.0             5
4        0.0  0.000000  ...                0.0             4
...      ...       ...  ...                ...           ...
1495     1.0  0.725806  ...                0.0             4
1496     1.0  0.838710  ...                0.0             9
1497     1.0  0.080645  ...                0.0             9
1498     1.0  0.935484  ...                0.0             5
1499     0.0  0.064516  ...                0.0             5

[1500 rows x 26 columns]

In [207]:
final_df.to_csv('final_df.csv', index=False)

In [208]:
final_df.head()

   Gender       Age  ...  Occupation_Writer  Stress Level
0     1.0  0.370968  ...                0.0            10
1     1.0  0.387097  ...                0.0             5
2     0.0  0.435484  ...                0.0             7
3     1.0  0.096774  ...                1.0             5
4     0.0  0.000000  ...                0.0             4

[5 rows x 26 columns]